name: LobbySystem
version: '1.3.2  pre-Build: 132.13'
author: [SLINIcraftet204,Dragonhard117]
main: de.dragonhard.lobby.Main

commands:
  warp:
    usage:
    description: keine Information!
    permission:
  spawn:
    usage:
    description: keine Information!
    permission:
  autowarp:
    usage:
    description: keine Informmation!
    permission:
  InvWarp:
    usage:
    description: keine Information!
    permission:
  block:
    usage:
    description: keine Information!
    permission: