name: LobbySystem
version: '1.5.0  beta-Build: 150.5'
author: Dragonhard117
main: de.dragonhard.lobby.Main
load: STARTUP

commands:
  msg:
    usage:
    description: Zum Senden einer Privaten Nachricht
    permission:
