name: LobbySystem
version: '1.3.7  beta-Build: 137.4'
author: Dragonhard117
main: de.dragonhard.lobby.Main

commands:
  warp:
    usage:
    description: zum erstellen eines Teleport punktes
    permission:
  spawn:
    usage:
    description: keine Information!
    permission:
  autowarp:
    usage:
    description: keine Informmation!
    permission:
  InvWarp:
    usage:
    description: zum erstellen eines Minispiel Teleport
    permission:
  block:
    usage:
    description: keine Information!
    permission:
  coins:
    usage:
    description: keine Information!
    permission:
  chclear:
    usage:
    description: zum leeren des Chats
    permission:
  crServer:
    usage:
    description: zum erstellen eines Servers!
    permission: